FROM ubuntu:18.04

# Install needed system tools
# update first
RUN apt-get -q update
RUN apt-get -q install tzdata -y

# install system build tools needed by gridlabd
RUN apt-get -q install git -y
RUN apt-get -q install unzip -y
RUN apt-get -q install autoconf -y
RUN apt-get -q install libtool -y
RUN apt-get -q install g++ -y
RUN apt-get -q install gcc -y
RUN apt-get -q install cmake -y 
RUN apt-get -q install flex -y
RUN apt-get -q install bison -y
RUN apt-get -q install libcurl4-gnutls-dev -y
RUN apt-get -q install libncurses5-dev -y
RUN apt-get -q install liblzma-dev -y
RUN apt-get -q install libssl-dev -y
RUN apt-get -q install libbz2-dev -y
RUN apt-get -q install libffi-dev -y
RUN apt-get -q install zlib1g-dev -y
RUN apt-get -q install curl -y
RUN apt-get -q install subversion -y
# converter support
RUN apt-get -q install mdbtools -y
RUN apt-get -q install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt-get -q install gawk -y



WORKDIR "/usr/local/src"
RUN curl https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz > Python-3.9.6.tgz
RUN tar xzf Python-3.9.6.tgz 
WORKDIR "/usr/local/src/Python-3.9.6"
RUN ./configure --prefix=/usr/local --enable-optimizations --with-system-ffi --with-computed-gotos --enable-loadable-sqlite-extensions CFLAGS="-fPIC"
RUN make -j 12
RUN make altinstall
RUN /sbin/ldconfig /usr/local/lib
RUN ln -sf /usr/local/bin/python3.9 /usr/local/bin/python3
RUN ln -sf /usr/local/bin/python3.9-config /usr/local/bin/python3-config
RUN ln -sf /usr/local/bin/pydoc3.9 /usr/local/bin/pydoc
RUN ln -sf /usr/local/bin/idle3.9 /usr/local/bin/idle
RUN ln -sf /usr/local/bin/pip3.9 /usr/local/bin/pip3
RUN /usr/local/bin/python3 -m pip install matplotlib Pillow pandas numpy networkx pytz pysolar PyGithub scikit-learn xlrd boto3
RUN /usr/local/bin/python3 -m pip install IPython censusdata
WORKDIR "/usr/local/src"
RUN rm -f Python-3.9.6.tgz
RUN pip3 install --upgrade pip


RUN export PYTHONPATH="."
RUN export PATH=/usr/local/bin:$PATH
RUN export MAKEFLAGS=-j20
RUN export PYTHONSETUPFLAGS="-j20"

# #mono
RUN apt install gnupg ca-certificates -y
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | tee /etc/apt/sources.list.d/mono-official-stable.list
#RUN apt update -y
#doxygen
RUN apt-get install doxygen -y

# clone gridlabd 
WORKDIR "/usr/local/src"
RUN git clone https://github.com/slacgismo/gridlabd
WORKDIR "/usr/local/src/gridlabd"
RUN autoreconf -isf && ./configure

RUN make system
RUN /usr/local/bin/python3 -m pip install --upgrade numpy

#ubuntu 22.04
#*** buffer overflow detected ***: terminatedtest/test_IEEE123_link_outages.glm...

#ubunu 20.04 & 18.04
# always have issue as debian
# /usr/bin/ld: /usr/local/lib/python3.9/config-3.9-x86_64-linux-gnu/libpython3.9.a(posixmodule.o): in function `os_openpty_impl':
# /usr/local/src/Python-3.9.6/./Modules/posixmodule.c:7192: undefined reference to `openpty'
# /usr/bin/ld: /usr/local/lib/python3.9/config-3.9-x86_64-linux-gnu/libpython3.9.a(posixmodule.o): in function `os_forkpty_impl':
# /usr/local/src/Python-3.9.6/./Modules/posixmodule.c:7293: undefined reference to `forkpty'

#   CXXLD    module/tape_file/tape_file.la
# /usr/bin/ld: /usr/local/lib/python3.9/config-3.9-x86_64-linux-gnu/libpython3.9.a(posixmodule.o): in function `os_openpty_impl':
# /usr/local/src/Python-3.9.6/./Modules/posixmodule.c:7192: undefined reference to `openpty'
# /usr/bin/ld: /usr/local/lib/python3.9/config-3.9-x86_64-linux-gnu/libpython3.9.a(posixmodule.o): in function `os_forkpty_impl':
# /usr/local/src/Python-3.9.6/./Modules/posixmodule.c:7293: undefined reference to `forkpty'
# collect2: error: ld returned 1 exit status
# make[1]: *** [Makefile:3176: gridlabd.bin] Error 1
# make[1]: *** Waiting for unfinished jobs....
# /usr/bin/ld: /usr/local/lib/python3.9/config-3.9-x86_64-linux-gnu/libpython3.9.a(dynload_shlib.o): in function `_PyImport_FindSharedFuncptr':
# /usr/local/src/Python-3.9.6/./Python/dynload_shlib.c:100: undefined reference to `dlopen'
# /usr/bin/ld: /usr/local/src/Python-3.9.6/./Python/dynload_shlib.c:131: undefined reference to `dlsym'
# /usr/bin/ld: /usr/local/src/Python-3.9.6/./Python/dynload_shlib.c:100: undefined reference to `dlopen'
# /usr/bin/ld: /usr/local/src/Python-3.9.6/./Python/dynload_shlib.c:106: undefined reference to `dlerror'
# /usr/bin/ld: /usr/local/src/Python-3.9.6/./Python/dynload_shlib.c:87: undefined reference to `dlsym'
# /usr/bin/ld: /usr/local/lib/python3.9/config-3.9-x86_64-linux-gnu/libpython3.9.a(posixmodule.o): in function `os_openpty_impl':
# /usr/local/src/Python-3.9.6/./Modules/posixmodule.c:7192: undefined reference to `openpty'
# /usr/bin/ld: /usr/local/lib/python3.9/config-3.9-x86_64-linux-gnu/libpython3.9.a(posixmodule.o): in function `os_forkpty_impl':
# /usr/local/src/Python-3.9.6/./Modules/posixmodule.c:7293: undefined reference to `forkpty'
# collect2: error: ld returned 1 exit status
# make[1]: *** [Makefile:2734: module/revenue/revenue.la] Error 1
# /usr/local/src/gridlabd/gldcore/module.cpp: In function ‘MODULE* module_load(const char*, int, const char**)’:
# /usr/local/src/gridlabd/gldcore/module.cpp:416:42: warning: ‘%s’ directive output may be truncated writing up to 4096 bytes into a region of size 2047 [-Wformat-truncation=]
#   416 |  snprintf(pathname, sizeof(pathname)-1, "%s" DLEXT, file);
#       |                                          ^~
# In file included from /usr/include/stdio.h:867,
#                  from /usr/local/src/gridlabd/gldcore/gldcore.h:25,
#                  from /usr/local/src/gridlabd/gldcore/module.cpp:21:
# /usr/include/x86_64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output between 4 and 4100 bytes into a destination of size 2047
#    67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
#       |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#    68 |        __bos (__s), __fmt, __va_arg_pack ());
#       |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# make[1]: Leaving directory '/usr/local/src/gridlabd'
# make: *** [Makefile:6581: install] Error 2
# make: *** Waiting for unfinished jobs....
# root@d8aa09a39e97:/usr/local/src/gridlabd# 


#printenv

# PYTHONSETUPFLAGS=-j 20
# HOSTNAME=d8aa09a39e97
# PWD=/usr/local/src/gridlabd
# HOME=/root
# LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
# LESSCLOSE=/usr/bin/lesspipe %s %s
# MAKEFLAGS=-j20
# PYTHONPATH=.
# TERM=xterm
# LESSOPEN=| /usr/bin/lesspipe %s
# SHLVL=1
# PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# OLDPWD=/usr/local/src
# _=/usr/bin/printenv